### ISSUE TITLE
Mod ID is `modid` instead of `biospheres`

### ISSUE THREAD

**Issue by LemmaEOF** [coolsa/Biospheres#1]
Your [fabric.mod.json](https://github.com/coolsa/Modfest1.16/blob/Biosphere/src/main/resources/fabric.mod.json#L3) defines the mod ID to be `modid` instead of `biospheres`. This can cause various issues and make debugging more difficult.

**Comment by coolsa** [comment]
This should be fixed in the newest release, 0.0.2

Woops, my bad!
